### ISSUE TITLE
Expanded text selectable?

### ISSUE THREAD

**Issue by jinfagang** [jesusrp98/expand_widget#19]
thanks for this useful lib. is that possible add a property to make text can be selectable as well?

**Comment by jesusrp98** [comment]
I can implement this feature @jinfagang. What about adding a new boolean property called `isSelectable` that makes the base widget to use the `SelectableText` widget instead of a simple `Text`widget?

Do you need anything more from this feature?

**Comment by jinfagang** [comment]
@jesusrp98 Sorry for the late reply. I found another issue about this widget: when using it in a raw and which belongs to a listview, it will over take scroll gesture detector make the listview not able to scroll, except I scroll on area else.

**Comment by jesusrp98** [comment]
Yes, this behavior can be fixed by telling the widget to ignore gestures all togheter, it's ne only way :/

**Comment by jesusrp98** [comment]
About the selecting text option, this feature is harder to implement than I initially thought.
It'll be implemented in a future version.

**Comment by JamesMcIntosh** [comment]
Hi @jesusrp98, just wondering what were the issues you saw with SelectableText.

**Comment by eliper3** [comment]
Love your library. Looking for such a feature for selectable text as well. Thank you.

**Comment by jesusrp98** [comment]
Hey! So in the last couple days I've been investigating the `SelectableText` widget, and I found that it doesn't have a `overflow` property, so I should find another way to implement the overflow feature.

If you feel that you could help with this let me know!
Hopefully I could do some work on this weekend.

**Comment by jesusrp98** [comment]
So it seems that currently, the overflow visualization doesn't work properly on editable text widgets, as exposed [here](https://github.com/flutter/flutter/issues/80435).

There's an open PR at this moment by the one and only @pedromassango that fixes this issue.
When this get merged and carried to a stable Flutter release, I'll include this functionality to the package, since it's not difficult to implement.

I just don't want the `SelectableText` widget to not render overflow correctly, as a normal `Text` widget would do.
@jinfagang @JamesMcIntosh @eliper3

**Comment by jesusrp98** [comment]
This is now possible thanks the possiblity of revealing a section of the 'exandable' widget. You can use `ExpandChild`, and set the `collapsedVisibilityFactor` as you please.

Please feel free to reopen the issue if you think it's necessary :)

Sorry for taking so long to fix this :)
