### ISSUE TITLE
Vertical drag to expand/collapse behaviour

### ISSUE THREAD

**Issue by JamesMcIntosh** [jesusrp98/expand_widget#9]
The vertical drag to expand and collapse behaviour is a little bit unexpected.

1) When expanded text is in a scrollable list sometimes when you are trying to scroll the list then it expands the text.

2) Swiping to open / close the text ignores the direction you are swiping, i.e. if collapsed you can swipe up to expand, where I would expect swipe down only.

**Comment by jesusrp98** [comment]
I've commited a change that hopefully fixes your second issue: now it checks for the direction of the drag in order to perform an action. Maybe this also fixes your first issue.

Going to continue improving this package, planning to launch the next version in the coming weeks. If you find other issues, or have more feedback please let me know :)
Thank @JamesMcIntosh for taking the time to test all of this thing.
